language: node_js
env:
  - NODE_ENV=travis
node_js:
  - "4.4"
  - "5.10"
sudo: false
cache:
  directories:
    - node_modules
before_script:
  - npm install sequelize@^3.x
  - mysql -e 'create database shop;'
  - mysql -e 'create database blog;'
script:
  - npm run lint
  - npm test
