language: node_js
env:
  - NODE_ENV=travis
node_js:
  - "4"
  - "lts/*"
  - "node"
sudo: false
cache:
  directories:
    - node_modules
before_script:
  - npm install sequelize@^3.x
script:
  - npm run lint
  - npm test
after_script:
  - npm run coveralls
